/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TextOptions {
  tries?: number
  minWords?: number
  maxWords?: number
}
export declare class MarkovText {
  constructor(data: string)
  generate(options?: TextOptions | undefined | null): string | null
  generateAsync(options?: TextOptions | undefined | null): Promise<string | null>
  generateWithStart(start: string, options?: TextOptions | undefined | null): string | null
  generateWithStartAsync(start: string, options?: TextOptions | undefined | null): Promise<string | null>
  generateWithStarts(starts: Array<string>, options?: TextOptions | undefined | null): string | null
  generateMany(count: number, options?: TextOptions | undefined | null): Array<string>
  generateManyAsync(count: number, options?: TextOptions | undefined | null): Promise<Array<string>>
}
export declare class MarkovVocab {
  constructor()
  toToken(word: string): number
  toTokenOpt(word: string): number | null
  toWord(token: number): string
}
export declare class StringChain {
  static createEmpty(begin: string, end: string): StringChain
  static fromData(data: Array<Array<string>>, begin: string, end: string): StringChain
  next(state: Array<string>): string
  generate(initState?: Array<string> | undefined | null): Array<string>
  findInitStates(start: string): Array<Array<string>>
}
